- id: DS001
  file: latest_tag.rego
- id: DS002
  file: root_user.rego
- id: DS004
  file: port22.rego
- id: DS005
  file: add_instead_of_copy.rego
- id: DS006
  file: copy_from_references_current_from_alias.rego
- id: DS007
  file: multiple_entrypoint_instructions_listed.rego
- id: DS008
  file: unix_ports_out_of_range.rego
- id: DS009
  file: workdir_path_not_absolute.rego
- id: DS010
  file: run_using_sudo.rego
- id: DS011
  file: copy_with_more_than_two_arguments_not_ending_with_slash.rego
- id: DS012
  file: same_alias_in_different_froms.rego
- id: DS013
  file: run_command_cd_instead_of_workdir.rego
- id: DS014
  file: run_using_wget_and_curl.rego
- id: DS015
  file: yum_clean_all_missing.rego
- id: DS016
  file: multiple_cmd_instructions_listed.rego
- id: DS017
  file: update_instruction_alone.rego
- id: DS018
  file: copy_from_without_from_alias_defined_previously.rego
- id: DS019
  file: missing_dnf_clean_all.rego
- id: DS020
  file: missing_zypper_clean.rego
- id: DS021
  file: apt_get_missing_yes_flag_to_avoid_manual_input.rego
- id: DS022
  file: maintainer_is_deprecated.rego
- id: DS023
  file: multiple_healthcheck_instructions.rego
- id: DS024
  file: run_apt_get_dist_upgrade.rego
