name: adapter-lint
on:
  pull_request:
jobs:
  adapter-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: lint
        run: make adapter-lint
