name: update outdated-api policy
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 0" # Sunday midnight
permissions:
  contents: write
env:
  GH_USER: aqua-bot
jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_COMMIT_TOKEN }}
      - name: Fetch outdated API data from trivy-db-data repo
        id: outdatedapi
        uses: fjogeleit/http-request-action@v1
        with:
         url: 'https://raw.githubusercontent.com/aquasecurity/trivy-db-data/main/k8s/api/k8s-outdated-api.json'
         method: 'GET'
      - name: embed outdatedapi-data with in dynamic rego policy
        run: |
          make outdated-api-updated data=${{ toJson(steps.outdatedapi.outputs.response) }}
      - name: commit and push updated outdated-api policy when changes found
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update outdated-api policy data
          push_options: --force   
