name: Release
on:
  push:
    tags:
      - "v*"
env:
  GH_USER: aqua-bot
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Creat bundle
        run: make bundle
      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Packages Container registry
        run: |
          tags=(latest ${{ env.RELEASE_VERSION}} ${{env.MINOR_VERSION }} ${{ env.MAJOR_VERSION }})
          for tag in ${tags[@]}; do
              oras push ghcr.io/${{ github.repository }}:${tag} \
              --config /dev/null:application/vnd.cncf.openpolicyagent.config.v1+json \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done
