name: test go
on:
  pull_request:
  merge_group:
  schedule:
  - cron:  0 23 * * *
jobs:
  build:
    name: building defsec
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      if: matrix.os != 'windows-latest'
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    - uses: actions/setup-go@v3
      if: matrix.os == 'windows-latest'
      with:
        go-version-file: go.mod
        cache: false

    - name: Run full tests
      run: make test
      shell: bash
