name: test go
on:
  pull_request:
  schedule:
  - cron:  0 23 * * *
jobs:
  build:
    name: building defsec
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    - run: go version

    - name: Run non-localstack tests
      if: matrix.os != 'ubuntu-latest'
      run: make test-no-localstack
      shell: bash
    - name: Run full tests
      if: matrix.os == 'ubuntu-latest'
      run: make test
      shell: bash
