name: test rego bundle
on:
  pull_request:
  merge_group:
jobs:
  opa-tests:
    name: OPA tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build bundle
        run: make bundle
      - name: Setup OPA
        uses: ./.github/actions/setup-opa
      - name: Check bundle
        run: opa inspect bundle.tar.gz
