name: test trivy
on:
  push:
    branches-ignore:
      - "master"
  pull_request:

env:
  TRIVY_DIR: "trivy-repo"
  DEFSEC_DIR: "defsec-repo"

jobs:
  test:
    name: Test trivy
    defaults:
      run:
        working-directory: ${{ env.TRIVY_DIR }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout defsec
        uses: actions/checkout@v3
        with:
          repository: aquasecurity/defsec
          path: ${{ env.DEFSEC_DIR }}

      - name: Checkout trivy
        uses: actions/checkout@v3
        with:
          repository: aquasecurity/trivy
          path: ${{ env.TRIVY_DIR }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: "${{ env.TRIVY_DIR }}/go.mod"
          cache-dependency-path: "${{ env.TRIVY_DIR }}/go.sum"

      - name: Replace defsec
        run: |
          go mod edit -replace "github.com/aquasecurity/defsec=../${{ env.DEFSEC_DIR }}"

      - name: Install tools
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.8.0
          working_directory: ${{ env.TRIVY_DIR }}

      - name: Run unit tests
        run: mage test:unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TRIVY_DIR }}
    steps:
      - name: Checkout defsec
        uses: actions/checkout@v3
        with:
          repository: aquasecurity/defsec
          path: ${{ env.DEFSEC_DIR }}

      - name: Checkout trivy
        uses: actions/checkout@v3
        with:
          repository: aquasecurity/trivy
          path: ${{ env.TRIVY_DIR }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: "${{ env.TRIVY_DIR }}/go.mod"
          cache-dependency-path: "${{ env.TRIVY_DIR }}/go.sum"

      - name: Replace defsec
        run: |
          go mod edit -replace "github.com/aquasecurity/defsec=../${{ env.DEFSEC_DIR }}"

      - name: Install tools
        uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.8.0
          working_directory: ${{ env.TRIVY_DIR }}

      - name: Run integration tests
        run: mage test:integration

      - name: Run k8s integration tests
        run: mage test:k8s

      - name: Run module integration tests
        run: mage test:module
