name: verify schema
on:
  pull_request:
  merge_group:
jobs:
  build:
    name: verifying schema
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - run: go run ./cmd/schema verify
  